### PR TITLE
Install `atk` in github actions

### PR DESCRIPTION
**Pull request by dastansam**

### CODE REVIEW

**Comment by nazar-pc** [comment]
Can you open PRs when you have proper description written already, please?

**Comment by dastansam** [comment]
> Can you open PRs when you have proper description written already, please?

it's a draft PR though, I wanted to see if the CI passes

**Comment by nazar-pc** [comment]
We generally don't open PRs until they are ready for review. To check CI you can trigger it for any branch at https://github.com/autonomys/space-acres/actions or else everyone subscribed to the repo will get an email every time you push a commit or do something like that, which gets very annoying very quickly.

**Comment by dastansam** [comment]
can be part of #288

**Pull request closed without merging**
