### PR TITLE
Add icons build script

### PR DESCRIPTION
**Pull request by dastansam**
this PR adds a build script for bundling icons with `relm4-icons` crate. This is a companion PR of https://github.com/Relm4/icons/pull/19 and will enable us to upgrade that crate

### CODE REVIEW

**Comment by nazar-pc** [comment]
Would you mind leaving some comment in PR description? I'm not sure what is the purpose of this.

**Comment by nazar-pc** [comment]
Given how many conflicts there were in a single commit, wouldn't it be better to do rebase instead?

**Comment by nazar-pc** [comment]
Will set to draft until upstream at least receives a review. Do not want to merge something that points to a custom temporary fork.

**Comment by nazar-pc** [comment]
Character escaping on Windows is not working properly

**Comment by nazar-pc** [comment]
@dastansam when do you plan to finish work here?

**Comment by dastansam** [comment]
> @dastansam when do you plan to finish work here?

this week, hopefully

**Comment by dastansam** [comment]
> Can you rebase on `main` and squash everything so we can see if CI works?

sure, can do the rebase, but my `relm4-icons` PR needs to be merged and released before that, no? or it's ok to point to my own fork?

**Comment by nazar-pc** [comment]
Sure, let's do that, just to see how it works. It'll also be easier for me to test on my end. We'll update it to upstream release once it is out.

**Comment by nazar-pc** [comment]
Ping?

**Comment by nazar-pc** [comment]
@dastansam we can switch to upstream git revision now since https://github.com/Relm4/icons/pull/19 was merged with TODO to switch to upstream release once it is available.

**Comment by dastansam** [comment]
> @dastansam we can switch to upstream git revision now since [Relm4/icons#19](https://github.com/Relm4/icons/pull/19) was merged with TODO to switch to upstream release once it is available.

sure, I had hard time pointing to the new build crate because it's not resolved by importing crate from `git`. Should the `relm4-icons` be converted to virtual workspace for that?

**Comment by dastanbeksamatov** [comment]
> Do you have log with errors you were getting? The repo does have a workspace, so should not be an issue to pull any packages from it.

yeah, simply trying to import build crate from git link will fail with "unresolved crate" error

**Comment by nazar-pc** [comment]
I have a successor branch that is up to date and built on top of https://github.com/Relm4/icons/pull/24, closing this.

Thanks for the heavy lifting here!

**Pull request closed without merging**
